# Generated by Django 4.2.4 on 2023-08-08 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assets_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tracking_records', to='Assets_tracker.device'),
        ),
    ]
