# Generated by Django 4.2.4 on 2023-08-09 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Assets_tracker', '0002_alter_tracking_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='assign_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
