# Generated by Django 4.2.4 on 2023-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets_tracker', '0003_alter_tracking_assign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='condition_checkout',
            field=models.TextField(blank=True, null=True),
        ),
    ]
